name: marl4tsc
channels:
  - pytorch
dependencies:
  - anaconda
  - cuda-toolkit=11.7.1
  - numpy=1.23.5
  - python=3.9.16
  - pip
  - pip:
    - matplotlib==3.6.3
    - scikit-learn==1.0.1
    - tensorflow==2.7.0
    - torch==1.13.1
    - torchaudio==0.13.1
    - torchvision==0.14.1
    - tqdm==4.64.1
    - gym==0.21.0
    - pfrl==0.3.0
    - traci==1.15.0
    - transformers==4.6.0
    - adapter-transformers==3.2.0
    - tensorboard==2.11.2